"""Generated by ICARUS-LEO config builder.

Experiment: cs2_m0_trace_LCD_s1

If you have the simulator engine, run:
    icarus run -r results_config_trace_m0.pickle config_trace_m0.py
and generate the interactive viewer with:
    python3 tools/generate_log_viewer.py results_config_trace_m0.pickle \
        -o viewer_config_trace_m0.html --n-viewable 1000

Otherwise, see https://github.com/gcampobello/ICARUS-LEO
for how to have it run.
"""
from icarus.util import Tree

LOG_LEVEL = 'WARNING'
PARALLEL_EXECUTION = False
N_REPLICATIONS = 1
RESULTS_FORMAT = 'PICKLE'

DATA_COLLECTORS = ['CACHE_HIT_RATIO', 'LEO_METRICS', 'SESSION_LOG']

EXPERIMENT_QUEUE = []

# --- Single experiment ---
experiment = Tree()
experiment['topology'] = {
        'name': 'LEO_DYN_IRIDIUM',
        'seed': 42,
        'n_receivers_per_gs': 1,
        'min_elevation_deg': 0.0,
        'receiver_distribution': 'uniform_global_safe',
        'receiver_placement_seed': 42,
        'n_snapshots': 1,
        'handover_source': 'snapshot',
        'handover_blackout_s': 0.0,
        'allow_gs_transit': False,
    }
experiment['workload'] = {
        'name': 'STATIONARY_CHUNKED',
        'n_contents': 100,
        'n_chunks': 50,
        'alpha': 1.0,
        'n_warmup': 6000,
        'n_measured': 4000,
        'rate': 1.0,
        'seed': 1,
    }
experiment['cache_placement'] = {
        'name': 'UNIFORM',
        'network_cache': 330,
    }
experiment['content_placement'] = {
        'name': 'UNIFORM_CHUNKED',
        'seed': 42,
    }
experiment['cache_policy'] = {
        'name': 'LRU',
    }
experiment['strategy'] = {
        'name': 'RETRY_LCD_LOSSY',
        'max_retries': 0,
        'retry_timeout_ms': 300.0,
        'content_size_bytes': 8192,
        'loss_model': {
            'name': 'COMPOSITE',
            'per_link_type': {
                'user_radio': {
                    'name': 'TRACE',
                    'trace_npz_path': 'LEO_downlink_loss-Ger0804-170001-1h.npz',
                    'seed': 1,
                },
                'gsl': {
                    'name': 'BERNOULLI',
                    'ber_gsl': 3e-8,
                    'seed': 1,
                },
                'isl_intra': {
                    'name': 'BERNOULLI',
                    'ber_isl': 3e-8,
                    'seed': 1,
                },
                'isl_inter': {
                    'name': 'BERNOULLI',
                    'ber_isl': 3e-8,
                    'seed': 1,
                },
            },
        },
    }
experiment['desc'] = 'cs2_m0_trace_LCD_s1'
EXPERIMENT_QUEUE.append(experiment)
