"""Generated by ICARUS-LEO config builder.

Experiment: cs1_dynamic_lossy_s1

Sweep axes (1):
  - strategy.name: ["RETRY_LCE_LOSSY", "RETRY_LCD_LOSSY", "RETRY_PROB_CACHE_LOSSY", "RETRY_CL4M_LOSSY"]

Total experiments: 4

If you have the simulator engine, run:
    icarus run -r results_config.pickle config.py
and generate the interactive viewer with:
    python3 tools/generate_log_viewer.py results_config.pickle \
        -o viewer_config.html --n-viewable 1000

Otherwise, see https://github.com/gcampobello/ICARUS-LEO
for how to have it run.
"""
from icarus.util import Tree
import itertools

LOG_LEVEL = 'WARNING'
PARALLEL_EXECUTION = False
N_REPLICATIONS = 1
RESULTS_FORMAT = 'PICKLE'

DATA_COLLECTORS = ['CACHE_HIT_RATIO', 'LEO_METRICS', 'SESSION_LOG']

EXPERIMENT_QUEUE = []

# --- Sweep: 4 experiments (4) ---
_strat_name_vals = ['RETRY_LCE_LOSSY', 'RETRY_LCD_LOSSY', 'RETRY_PROB_CACHE_LOSSY', 'RETRY_CL4M_LOSSY']

for _strat_name_v, in itertools.product(_strat_name_vals):
    experiment = Tree()
    experiment['topology'] = {
        'name': 'LEO_DYN_IRIDIUM',
        'seed': 42,
        'n_receivers_per_gs': 1,
        'min_elevation_deg': 0.0,
        'receiver_distribution': 'uniform_global_safe',
        'receiver_placement_seed': 42,
        'n_snapshots': 100,
        'handover_blackout_s': 1.0,
        'allow_gs_transit': False,
    }
    experiment['workload'] = {
        'name': 'STATIONARY_CHUNKED',
        'n_contents': 100,
        'n_chunks': 1,
        'alpha': 1.0,
        'n_warmup': 20000,
        'n_measured': 30000,
        'rate': 1.0,
        'seed': 1,
    }
    experiment['cache_placement'] = {
        'name': 'UNIFORM',
        'network_cache': 6.6,
    }
    experiment['content_placement'] = {
        'name': 'UNIFORM_CHUNKED',
        'seed': 42,
    }
    experiment['cache_policy'] = {
        'name': 'LRU',
    }
    experiment['strategy'] = {
        'name': _strat_name_v,
        'max_retries': 0,
        'retry_timeout_ms': 300.0,
        't_tw': 10,
        'content_size_bytes': 8192,
        'loss_model': {
            'name': 'BERNOULLI',
            'ber_gsl': 2e-6,
            'ber_isl': 2e-6,
            'ber_access': 0,
            'ber_user_radio': 2e-6,
            'seed': 1,
        },
    }
    experiment['desc'] = 'cs1_dynamic_lossy_s1' + f' [strat_name={_strat_name_v}]'
    EXPERIMENT_QUEUE.append(experiment)
